SklepInternetowy/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SklepInternetowy.BL.DTOs.Order;
using SklepInternetowy.BL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace SklepInternetowy.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult All(string search, string currentFilter, int? pageNumber, string sortOrder = "DateCreated", int pageSize = 15)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["StatusSortParam"] = sortOrder == "Status" ? "status_desc" : "Status";
            ViewData["DateCreatedSortParm"] = sortOrder == "DateCreated" ? "dateCreated_desc" : "DateCreated";
            ViewData["CostSortParam"] = sortOrder == "Cost" ? "cost_desc" : "Cost";

            if (search != null)
            {
                pageNumber = 1;
            }
            else
            {
                search = currentFilter;
            }
            string orderMethod = "Asc";

            switch (sortOrder)
            {
                case "status_desc":
                    orderMethod = "Desc";
                    sortOrder = "Status";
                    break;
                case "dateCreated_desc":
                    orderMethod = "Desc";
                    sortOrder = "DateCreated";
                    break;
                case "cost_desc":
                    orderMethod = "Desc";
                    sortOrder = "Cost";
                    break;
                default:
                    break;
            }
            pageNumber = pageNumber ?? 1;
            ViewData["CurrentFilter"] = search;
            var result = _orderService.GetAllOrders(pageNumber.Value, pageSize, sortOrder, orderMethod, search);
            return View(result);
        }
        public ActionResult My()
        {
            List<GetListOrderDTO> result = _orderService.GetCurrentUserOrders();
            
            return View(result);
        }
        public ActionResult Details(Guid id)
        {
            GetOrderDTO item = _orderService.GetOrderDTOById(id);
            return View(item);
        }
        
        public ActionResult Invoice(Guid id)
        {
            FileDTO item = _orderService.GetOrderInvoice(id);
            return File(item.File,"application/pdf",item.Name);
        }

        [Authorize(Roles = "Admin,Manager")]
        public IActionResult Edit(Guid id)
        {
            ChangeStatusDTO item = _orderService.GetChangeOrderStatus(id);
            return View(item);
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind] ChangeStatusDTO dto)
        {
            if (ModelState.IsValid)
            {
                _orderService.ChangeOrderStatus(dto);
                return RedirectToAction("All");
            }
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] CreateOrderDTO createDTO)
        {
            if (ModelState.IsValid)
            {
                string result = await _orderService.CreateOrder(createDTO);
                return Redirect(result);
            }
            return View(createDTO);
        }

        public IActionResult PCMaker()
        {
            CreateOrderDTO dto = _orderService.GetWorkingOrder();
            if (dto != null)
            {
                ViewBag.locationSelect = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(dto.CurrentUserLocations, "Value", "Name");
                var sum = 0.00M;
                foreach (var item in dto.Products)
                    sum += item.Price * item.Quantity;
                ViewBag.summary = sum;
            }
            else
                ViewBag.summary = 0;
            return View(dto);
        }

        public IActionResult AddOrderProduct(Guid id)
        {
            CreateOrderProductDTO item = _orderService.GetCreateOrderProductDTO(id);
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteOrderItem(Guid id)
        {
            _orderService.RemoveOrderItem(id);
            return RedirectToAction("PCMaker");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddOrderProductConfirmed(Guid id)
        {
            _orderService.AddOrderProduct(id);
            return RedirectToAction("PCMaker");
        }

        //PŁATNOŚCI
        [AllowAnonymous]
        [HttpPost]
        public HttpResponseMessage StatusReceiver([FromBody] PaymentUpdateDTO item)
        {
            string ipAddress = HttpContext.Connection.RemoteIpAddress.ToString();
            HttpStatusCode result = _orderService.UpdatePaymentStatus(item, ipAddress);
            if (result == HttpStatusCode.OK)
            {
                var resp = new HttpResponseMessage(HttpStatusCode.OK)
                {
                    Content = new StringContent("OK", System.Text.Encoding.UTF8, "text/plain")
                };
                return resp;
            }
            else return new HttpResponseMessage(result);
        }
    }
}

SklepInternetowy/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SklepInternetowy.BL.DTOs.Product;
using SklepInternetowy.BL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SklepInternetowy.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Index(int? type, string search, string currentFilter, int? pageNumber, string sortOrder = "DateCreated", int pageSize = 15)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TypeSortParam"] = sortOrder == "Type" ? "type_desc" : "Type";
            ViewData["DateCreatedSortParm"] = sortOrder == "DateCreated" ? "dateCreated_desc" : "DateCreated";
            ViewData["UnitsSortParam"] = sortOrder == "AvailableUnits" ? "AvailableUnits_desc" : "AvailableUnits";
            ViewData["NameSortParam"] = sortOrder == "Name" ? "name_desc" : "Name";

            if (search != null)
            {
                pageNumber = 1;
            }
            else
            {
                search = currentFilter;
            }
            string orderMethod = "Asc";

            switch (sortOrder)
            {
                case "type_desc":
                    orderMethod = "Desc";
                    sortOrder = "Type";
                    break;
                case "dateCreated_desc":
                    orderMethod = "Desc";
                    sortOrder = "DateCreated";
                    break;
                case "AvailableUnits_desc":
                    orderMethod = "Desc";
                    sortOrder = "AvailableUnits";
                    break;
                case "name_desc":
                    orderMethod = "Desc";
                    sortOrder = "Name";
                    break;
                default:
                    break;
            }
            pageNumber = pageNumber ?? 1;
            ViewData["CurrentFilter"] = search;

            var result = _productService.GetAllProducts(pageNumber.Value, pageSize, sortOrder, orderMethod, type, search);

            return View(result);
        }
        [Authorize]
        public ActionResult Type(int type, string search, string currentFilter, int? pageNumber, string sortOrder = "DateCreated", int pageSize = 15)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["PriceSortParam"] = sortOrder == "Price" ? "price_desc" : "Price";
            ViewData["NameSortParam"] = sortOrder == "Name" ? "name_desc" : "Name";

            if (search != null)
            {
                pageNumber = 1;
            }
            else
            {
                search = currentFilter;
            }
            string orderMethod = "Asc";

            switch (sortOrder)
            {
                case "price_desc":
                    orderMethod = "Desc";
                    sortOrder = "Price";
                    break;
                case "name_desc":
                    orderMethod = "Desc";
                    sortOrder = "Name";
                    break;
                default:
                    break;
            }
            pageNumber = pageNumber ?? 1;
            ViewData["CurrentFilter"] = search;

            SklepInternetowy.BL.Models.PaginatedList<SklepInternetowy.BL.DTOs.Product.ListProductTypeDTO> result = _productService.GetTypeProducts(pageNumber.Value, pageSize, sortOrder, orderMethod, type, search);

            return View(result);
        }

        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewProductDTO item = _productService.GetById(id.Value);

            return View(item);
        }

        [Authorize(Roles = "Admin,Manager")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Name,Price,AvailableUnits,Type,Description")] CreateProductDTO item)
        {
            if (ModelState.IsValid)
            {
                Guid id = _productService.CreateProduct(item);
                return RedirectToAction(nameof(Details), new { id = id });
            }
            return View(item);
        }

        [Authorize(Roles = "Admin,Manager")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            EditProductDTO item = _productService.GetEditProduct(id.Value);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("Id,Name,Price,AvailableUnits,Type,Description")] EditProductDTO item)
        {
            if (ModelState.IsValid)
            {
                _productService.UpdateProduct(item);

                return RedirectToAction(nameof(Details), new { id = item.Id });
            }
            return View(item);
        }

        [Authorize(Roles = "Admin,Manager")]
        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = _productService.GetDeleteProductDTO(id);

            return View(item);
        }

        [Authorize(Roles = "Admin,Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _productService.DeleteProduct(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

SklepInternetowy/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SklepInternetowy.BL.DTOs.Order;
using SklepInternetowy.BL.DTOs.User;
using SklepInternetowy.BL.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SklepInternetowy.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        public ActionResult Edit()
        {
            EditUserDTO dto = _userService.GetCurrentUser();
            return View(dto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind] EditUserDTO dto)
        {
            if (ModelState.IsValid)
            {
                Guid id = _userService.EditCurrentUser(dto);
                return RedirectToAction(nameof(Details), new { id = id });
            }
            return View(dto);
        }
        #region endpointy klienta

        #region lokalizacje użytkownika
        [Authorize(Roles = "Admin,Client")]
        public ActionResult Locations()
        {
            List<ListUserLocationDTO> result = _userService.GetUserLocations();
            return View(result);
        }
        [Authorize(Roles = "Admin,Client")]
        public ActionResult LocationDetails(Guid id)
        {
            GetLocationDTO item = _userService.GetLocationDetails(id);
            return View(item);
        }
        [Authorize(Roles = "Admin,Client")]
        public ActionResult CreateLocation()
        {
            return View();
        }
        [Authorize(Roles = "Admin,Client")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLocation([Bind] CreateLocationDTO createDTO)
        {
            if (ModelState.IsValid)
            {
                _userService.AddUserLocation(createDTO);
                return RedirectToAction(nameof(Locations));
            }
            return View(createDTO);
        }
        [Authorize(Roles = "Admin,Client")]
        public ActionResult DeleteLocation(Guid id)
        {
            string locationName = _userService.DeleteUserLocation(id);
            return View(locationName);
        }
        [Authorize(Roles = "Admin,Client")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteLocationConfirmed(Guid id)
        {
            _userService.DeleteUserLocation(id);
            return RedirectToAction(nameof(Locations));
        }

        #endregion
        #endregion


        #region zarządzanie użytkownikami - CRUD
        [Authorize(Roles = "Admin,Manager")]
        public ActionResult Index(string search, string currentFilter, int? pageNumber, string sortOrder = "DateCreated", int pageSize = 15)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["DateCreatedSortParm"] = sortOrder == "DateCreated" ? "dateCreated_desc" : "DateCreated";
            ViewData["Email"] = sortOrder == "Email" ? "email_desc" : "Email";
            ViewData["UserName"] = sortOrder == "UserName" ? "userName_desc" : "UserName";

            if (search != null)
            {
                pageNumber = 1;
            }
            else
            {
                search = currentFilter;
            }
            string orderMethod = "Asc";

            switch (sortOrder)
            {
                case "type_desc":
                    orderMethod = "Desc";
                    sortOrder = "Type";
                    break;
                case "dateCreated_desc":
                    orderMethod = "Desc";
                    sortOrder = "DateCreated";
                    break;
                case "email_desc":
                    orderMethod = "Desc";
                    sortOrder = "Email";
                    break;
                case "userName_desc":
                    orderMethod = "Desc";
                    sortOrder = "UserName";
                    break;
                default:
                    break;
            }
            pageNumber = pageNumber ?? 1;
            ViewData["CurrentFilter"] = search;
            var users = _userService.GetUsers(pageNumber.Value, pageSize, sortOrder, orderMethod, search);

            return View(users);
        }


        [Authorize]
        public ActionResult Details(Guid? id)
        {                
            DetailsUserDTO result = _userService.GetUserDetails(id);
            return View(result);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind] CreateUserDTO createDTO)
        {
            if (ModelState.IsValid)
            {
                Guid id = await _userService.CreateUser(createDTO);
                return RedirectToAction(nameof(Details), new { id = id });
            }
            return View(createDTO);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid id)
        {
            DeleteUserDTO dto = _userService.GetDeleteUserDTO(id);
            return View(dto);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            _userService.DeleteUser(id);
            return RedirectToAction(nameof(Index));
        }
        #endregion

    }
}

SklepInternetowy/Views/Order/Details.cshtml
@model SklepInternetowy.BL.DTOs.Order.GetOrderDTO

<div class="form-wrapper">
    <dl>
        <dt>
            Numer zamówienia
        </dt>
        <dd>
            @Model.Id
        </dd>
        <dt>
            Data utworzenia
        </dt>
        <dd>
            @Model.DateCreated.ToString("yyyy.MM.dd")
        </dd>
        <dt>
            Koszt zamówienia
        </dt>
        <dd>
            @Model.Cost.ToString("G")
        </dd>
        <dt>
            Status
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            Adres dostawy
        </dt>
        <dd>
            @Model.Location
        </dd>
    </dl>
</div>
<div class="table-wrapper">
    <table class="text-white table table-responsive-sm">
        <thead>
            <tr>
                <th>
                    Nazwa
                </th>
                <th>
                    Ilość
                </th>
                <th>
                    Cena
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderProducts)
            {
                <tr>
                    <td>
                        <a asp-controller="Product" asp-action="Details" asp-route-id="@item.Id">@item.Name</a>
                    </td>
                    <td>
                        @item.Quantity
                    </td>
                    <td>
                        @item.Price.ToString("G")
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="d-flex">
    @if (Model.IsAdmin)
    {
        <a class="form-wrapper-btn" asp-action="Edit" asp-route-id="@Model.Id">Zmień status</a>
    }
    @if (Model.Status == SklepInternetowy.Core.Enums.OrderStatus.Zrealizowane)
    {
        <a class="form-wrapper-btn" asp-action="Invoice" asp-route-id="@Model.Id">Faktura</a>
    }
    <a href="##" class="form-wrapper-btn" onClick="history.go(-1); return false;">Powrót</a>
</div>

SklepInternetowy/Views/Order/PCMaker.cshtml
@model SklepInternetowy.BL.DTOs.Order.CreateOrderDTO

<div class="flex-parent-row">
    <div class="flex-parent-child">
        <div class="child-item">
            <div>
                <div>
                    @if (Model?.Cpu != null)
                    {
                        <div class="d-flex flex-row justify-content-between">
                            <span>@Model.Cpu.Name</span>
                            <span>Cena: @Model.Cpu.Price</span>
                            <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@Model.Cpu.Id">
                                <button type="submit">&#10006;</button>
                            </form>
                        </div>
                    }
                    else
                    {
                        <span>Nie wybrano procesora</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="0">Wybierz</a>
                </div>
            </div>
            <div>
                <div>
                    @if (Model?.Cooler != null)
                    {
                        <div class="d-flex flex-row justify-content-between">
                            <span>@Model.Cooler.Name</span>
                            <span>Cena: @Model.Cooler.Price</span>
                            <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@Model.Cooler.Id">
                                <button type="submit">&#10006;</button>
                            </form>
                        </div>
                    }
                    else
                    {
                        <span>Nie wybrano chłodzenia</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="1">Wybierz</a>
                </div>
            </div>
        </div>
        <div class="child-item">
            <div class="single-item">
                <div>
                    @if (Model?.Gpu != null)
                    {
                        <div class="d-flex flex-row justify-content-between">
                            <span>@Model.Gpu.Name</span>
                            <span>Cena: @Model.Gpu.Price</span>
                            <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@Model.Gpu.Id">
                                <button type="submit">&#10006;</button>
                            </form>
                        </div>
                    }
                    else
                    {
                        <span>Nie wybrano karty</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="8">Wybierz</a>
                </div>
            </div>
        </div>
        <div class="child-item">
            <div class="single-item">
                <div class="list-elements">
                    @if (Model?.Additional.Count > 0)
                    {
                        @foreach (var item in Model.Additional)
                        {
                            <div class="d-flex flex-row justify-content-between">
                                <span class="first-span">@item.Name</span>
                                <span class="second-span">@item.Quantity</span>
                                <span class="third-span">Cena: @(item.Price*item.Quantity)</span>
                                <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@item.Id">
                                    <button type="submit">&#10006;</button>
                                </form>
                            </div>
                        }
                    }
                    else
                    {
                        <span>Nie wybrano akcesoriów</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="9">Dodaj</a>
                </div>
            </div>
        </div>
    </div>
    <div class="flex-parent-child">
        <div class="child-item flex-grow-1">
            <div class="single-item">
                <div class="list-elements align-items-center w-100">
                    <div class="list-summary justify-content-between w-100">
                        <span class="align-self-center">Podsumowanie</span>
                        @if (Model?.Products.Count > 0)
                            @foreach (var item in Model?.Products)
                            {
                                <div class="summary-item">
                                    <span class="first-span">@item.Name</span><span class="second-span">@item.Price</span><span class="third-span">@item.Quantity</span>
                                </div>
                            }
                        <span>Do zapłaty: @ViewBag.summary zł</span>
                    </div>
                    <form asp-action="Create">
                        <div class="form-group w-100 d-flex flex-column align-items-center">
                            <label asp-for="SelectedLocation" class="control-label">Adres dostawy</label>
                            @if (Model?.CurrentUserLocations == null || Model.CurrentUserLocations.Count == 0)
                            {
                                <a class="form-wrapper-btn" asp-controller="User" asp-action="CreateLocation">Utwórz adres</a>
                            }
                            else
                            {
                                <select asp-for="SelectedLocation" class="location-select" asp-items="ViewBag.locationSelect"></select>
                            }
                        </div>
                        @if (Model == null || Model.Products == null  || Model?.Products.Count == 0)
                        {
                            <span>Nie wybrano żadnego produktu!</span>
                        }
                        else
                        {
                            <button type="submit" class="form-wrapper-btn">Zamów i zapłać</button>
                        }
                    </form>
                </div>
            </div>
        </div>
        <div class="child-item" style=" height: 40%; ">
            <div class="single-item">
                <div>
                    @if (Model?.Pccase != null)
                    {
                        <div class="d-flex flex-row justify-content-between">
                            <span>@Model.Pccase.Name</span>
                            <span>Cena: @Model.Pccase.Price</span>
                            <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@Model.Pccase.Id">
                                <button type="submit">&#10006;</button>
                            </form>
                        </div>
                    }
                    else
                    {
                        <span>Nie wybrano obudowy</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="6">Wybierz</a>
                </div>
            </div>
        </div>
    </div>
    <div class="flex-parent-child">
        <div class="child-item">
            <div>
                <div>
                    @if (Model?.Ram != null)
                    {
                        <div class="d-flex flex-row justify-content-between">
                            <span>@Model.Ram.Name</span>
                            <span>Cena: @Model.Ram.Price</span>
                            <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@Model.Ram.Id">
                                <button type="submit">&#10006;</button>
                            </form>
                        </div>
                    }
                    else
                    {
                        <span>Nie wybrano RAMu</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="2">Wybierz</a>
                </div>
            </div>
            <div>
                <div>
                    @if (Model?.Mobo != null)
                    {
                        <div class="d-flex flex-row justify-content-between">
                            <span>@Model.Mobo.Name</span>
                            <span>Cena: @Model.Mobo.Price</span>
                            <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@Model.Mobo.Id">
                                <button type="submit">&#10006;</button>
                            </form>
                        </div>
                    }
                    else
                    {
                        <span>Nie wybrano płyty głównej</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="3">Wybierz</a>
                </div>
            </div>
        </div>
        <div class="child-item">
            <div class="single-item">
                <div class="list-elements">
                    @if (Model?.Disks.Count > 0)
                    {
                        @foreach (var item in Model.Disks)
                        {
                            <div class="d-flex flex-row justify-content-between">
                                <span class="first-span">@item.Name</span>
                                <span class="second-span">@item.Quantity</span>
                                <span class="third-span">Cena: @(item.Price*item.Quantity)</span>
                                <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@item.Id" asp-route-returnUrl="@Url.Action("PCMaker", "Order")">
                                    <button type="submit">&#10006;</button>
                                </form>
                            </div>
                        }
                    }
                    else
                    {
                        <span>Nie wybrano dysków</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="4">Dodaj SSD</a>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="5">Dodaj HDD</a>
                </div>
            </div>
        </div>
        <div class="child-item">
            <div class="single-item">
                <div>
                    @if (Model?.Psu != null)
                    {
                        <div class="d-flex flex-row justify-content-between">
                            <span>@Model.Psu.Name</span>
                            <span>Cena: @Model.Psu.Price</span>
                            <form class="delete-btn" asp-controller="Order" asp-action="DeleteOrderItem" asp-route-id="@Model.Psu.Id" asp-route-returnUrl="@Url.Action("PCMaker", "Order")">
                                <button type="submit">&#10006;</button>
                            </form>
                        </div>
                    }
                    else
                    {
                        <span>Nie wybrano zasilacza</span>
                    }
                </div>
                <div>
                    <a class="form-wrapper-btn" asp-controller="Product" asp-action="Type" asp-route-type="7">Wybierz</a>
                </div>
            </div>
        </div>
    </div>
</div>